### ISSUE TITLE
Load and Save file from toolbar

### ISSUE THREAD

**Issue by yuvalapidot** [yuvalapidot/voltron-config-editor#3]
Today, the yaml file is being loaded from the first / welcome page.
Instead, I want there to be no welcome page - opening the system will lead to empty canvas where we can start creating a new config from scratch.
On the top of the screen there should be a tool bar.
Currently, the only entry in the toolbar should file and in it only be load and save.

**Comment by mor0666** [comment]
Done in ToolBar component
